from __future__ import annotations

import json
from collections import Counter
from pathlib import Path

from .models import AuditReport, SourceEvidence


STATUS_ORDER = {
    "DRIFT": 0,
    "MISSING": 1,
    "UNOWNED": 2,
    "MANUAL": 3,
    "UNKNOWN": 4,
    "ORPHANED": 5,
    "PORTABLE": 6,
}


def write_json(report: AuditReport, path: Path) -> None:
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text(
        json.dumps(report.to_dict(), indent=2, sort_keys=False),
        encoding="utf-8",
    )


def _fmt_bytes(value: int) -> str:
    units = ["B", "KB", "MB", "GB"]
    size = float(value)
    for unit in units:
        if size < 1024 or unit == units[-1]:
            return f"{size:.0f} {unit}" if unit == "B" else f"{size:.1f} {unit}"
        size /= 1024
    return f"{value} B"


def _status_for_database(report: AuditReport, path: str) -> str:
    statuses = [
        audit.status
        for audit in report.table_audits
        if audit.database_path == path
    ]
    if not statuses:
        return "UNKNOWN"
    return sorted(statuses, key=lambda value: STATUS_ORDER.get(value, 99))[0]


def _evidence_lines(items: list[SourceEvidence], limit: int = 8) -> list[str]:
    output = []
    for item in items[:limit]:
        location = f"`{item.path}:{item.line}`"
        symbol = f" — `{item.symbol}`" if item.symbol else ""
        runtime = (
            f" ({item.runtime_reason})"
            if item.kind == "create_table" and item.runtime_reason
            else ""
        )
        output.append(f"- {location}{symbol}{runtime}")
    if len(items) > limit:
        output.append(f"- … {len(items) - limit} more")
    return output


def render_markdown(report: AuditReport) -> str:
    lines: list[str] = [
        "# Local Storage Audit",
        "",
        "> Generated by an explicitly invoked, read-only local SQLite inspection tool.",
        "> Databases are opened with SQLite URI `mode=ro` and `PRAGMA query_only=ON`.",
        "> Application bootstrap code is never imported or executed.",
        "",
        f"- Audit version: `{report.audit_version}`",
        f"- Scan root: `{report.scan_root}`",
        f"- SQLite databases discovered: **{len(report.databases)}**",
        f"- Observed tables audited: **{len(report.table_audits)}**",
        f"- Expected-but-missing tables: **{len(report.missing_tables)}**",
        "",
        "## Status vocabulary",
        "",
        "| Status | Meaning |",
        "|---|---|",
        "| `PORTABLE` | Schema creation exists and a runtime initialization path was proven statically. |",
        "| `MANUAL` | Schema creation exists only in a standalone script/SQL path. |",
        "| `UNOWNED` | A local table is consumed, but no schema creator was found. |",
        "| `MISSING` | Local-storage code or schema definitions expect a table not found in discovered DBs. |",
        "| `ORPHANED` | A local table exists, but no current SQLite consumer was detected. |",
        "| `DRIFT` | Observed schema is missing columns declared by discovered CREATE TABLE evidence. |",
        "| `UNKNOWN` | Creation exists, but runtime ownership/reproducibility could not be proven. |",
        "",
    ]

    status_counts = Counter(audit.status for audit in report.table_audits)
    status_counts.update(item.status for item in report.missing_tables)

    lines.extend(
        [
            "## Audit Summary",
            "",
            "| Status | Count |",
            "|---|---:|",
        ]
    )
    for status in sorted(status_counts, key=lambda value: STATUS_ORDER.get(value, 99)):
        lines.append(f"| `{status}` | {status_counts[status]} |")

    lines.extend(
        [
            "",
            "## SQLite Stores",
            "",
            "| Store | Scope | Size | Tables | Rows | Overall status |",
            "|---|---|---:|---:|---:|---|",
        ]
    )

    for database in report.databases:
        row_total = sum(
            table.row_count or 0
            for table in database.tables
            if table.row_count is not None
        )
        row_display = str(row_total) if database.readable else "—"
        status = _status_for_database(report, database.relative_path)
        lines.append(
            f"| `{database.relative_path}` | {database.scope} | "
            f"{_fmt_bytes(database.size_bytes)} | {len(database.tables)} | "
            f"{row_display} | `{status}` |"
        )

    for database in report.databases:
        lines.extend(
            [
                "",
                f"## `{database.relative_path}`",
                "",
                f"- Scope: `{database.scope}`",
                f"- Size: {_fmt_bytes(database.size_bytes)}",
                f"- SQLite header detected: `{str(database.sqlite_header).lower()}`",
                f"- Readable read-only: `{str(database.readable).lower()}`",
            ]
        )

        if database.error:
            lines.append(f"- Inspection error: {database.error}")
            continue

        lines.extend(
            [
                f"- `PRAGMA user_version`: `{database.user_version}`",
                f"- `PRAGMA schema_version`: `{database.schema_version}`",
                "",
                "### Tables",
                "",
                "| Table | Rows | Columns | PK | FKs | Indexes | Status |",
                "|---|---:|---:|---|---:|---:|---|",
            ]
        )

        audits_by_table = {
            audit.table.lower(): audit
            for audit in report.table_audits
            if audit.database_path == database.relative_path
        }

        for table in database.tables:
            audit = audits_by_table.get(table.name.lower())
            status = audit.status if audit else "UNKNOWN"
            pk_cols = [
                column.name
                for column in sorted(
                    table.columns,
                    key=lambda item: item.primary_key_position or 999,
                )
                if column.primary_key_position
            ]
            row_count = "—" if table.row_count is None else str(table.row_count)
            lines.append(
                f"| `{table.name}` | {row_count} | {len(table.columns)} | "
                f"{', '.join(pk_cols) or '—'} | {len(table.foreign_keys)} | "
                f"{len(table.indexes)} | `{status}` |"
            )

        for table in database.tables:
            audit = audits_by_table.get(table.name.lower())
            if not audit:
                continue
            lines.extend(
                [
                    "",
                    f"### `{table.name}`",
                    "",
                    f"**Status:** `{audit.status}`",
                    "",
                    audit.status_reason,
                    "",
                    "**Observed schema**",
                    "",
                    "| Column | Type | NOT NULL | Default | PK position |",
                    "|---|---|---|---|---:|",
                ]
            )
            for column in table.columns:
                default = "—" if column.default is None else f"`{column.default}`"
                lines.append(
                    f"| `{column.name}` | `{column.declared_type or ''}` | "
                    f"{'yes' if column.not_null else 'no'} | {default} | "
                    f"{column.primary_key_position or '—'} |"
                )

            if audit.missing_declared_columns:
                lines.extend(
                    [
                        "",
                        "**Schema drift detected**",
                        "",
                        "- Missing declared columns: "
                        + ", ".join(f"`{name}`" for name in audit.missing_declared_columns),
                    ]
                )

            lines.extend(["", "**Detected consumers**", ""])
            lines.extend(_evidence_lines(audit.consumers) or ["- None detected."])

            lines.extend(["", "**Detected schema creation**", ""])
            lines.extend(_evidence_lines(audit.creators) or ["- None detected."])

            if table.foreign_keys:
                lines.extend(["", "**Foreign keys**", ""])
                for fk in table.foreign_keys:
                    lines.append(
                        f"- `{fk.from_column}` → `{fk.target_table}.{fk.to_column}` "
                        f"(update `{fk.on_update}`, delete `{fk.on_delete}`)"
                    )

            if table.indexes:
                lines.extend(["", "**Indexes**", ""])
                for index in table.indexes:
                    lines.append(
                        f"- `{index.name}`"
                        f"{' UNIQUE' if index.unique else ''}: "
                        + ", ".join(f"`{column}`" for column in index.columns)
                    )

    if report.missing_tables:
        lines.extend(
            [
                "",
                "## Expected Tables Not Observed",
                "",
                "These findings are intentionally conservative: they mean the table was not "
                "found in the SQLite files discovered in this scan, not that the application "
                "can never create or obtain it elsewhere.",
                "",
            ]
        )
        for item in report.missing_tables:
            lines.extend(
                [
                    f"### `{item.table}`",
                    "",
                    f"**Status:** `{item.status}`",
                    "",
                    item.reason,
                    "",
                    "**Consumers**",
                    "",
                ]
            )
            lines.extend(_evidence_lines(item.consumers) or ["- None detected."])
            lines.extend(["", "**Schema definitions**", ""])
            lines.extend(_evidence_lines(item.creators) or ["- None detected."])

    db_literals = [
        item
        for item in report.source_scan.evidence
        if item.kind == "db_path_literal"
    ]
    if db_literals:
        lines.extend(
            [
                "",
                "## Database Path References in Source",
                "",
                "| Literal | Source | Symbol |",
                "|---|---|---|",
            ]
        )
        for item in db_literals:
            lines.append(
                f"| `{item.db_literal}` | `{item.path}:{item.line}` | "
                f"`{item.symbol or 'module'}` |"
            )

    lines.append("")
    return "\n".join(lines)


def write_markdown(report: AuditReport, path: Path) -> None:
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text(render_markdown(report), encoding="utf-8")
