from __future__ import annotations

import json
from collections import Counter, defaultdict
from pathlib import Path

from .models import CatalogRecord, SymbolRecord


def render_json(catalog: CatalogRecord) -> str:
    return json.dumps(catalog.to_dict(), indent=2, sort_keys=False) + "\n"


def _sig(symbol: SymbolRecord) -> str:
    params = []
    for p in symbol.parameters:
        text = p.name
        if p.annotation:
            text += f": {p.annotation}"
        if p.default is not None:
            text += f" = {p.default}"
        params.append(text)
    result = f"{symbol.name}({', '.join(params)})"
    if symbol.return_annotation:
        result += f" -> {symbol.return_annotation}"
    return result


def _one_line_doc(text: str | None) -> str:
    if not text:
        return ""
    return " ".join(text.strip().split()).replace("|", "\\|")


def render_markdown(catalog: CatalogRecord) -> str:
    public = [s for s in catalog.symbols if s.public and s.kind in {"function", "method"}]
    by_role = Counter(s.role or "other" for s in public)
    by_layer = Counter(s.layer or "other" for s in public)

    out: list[str] = [
        "# Backend Catalog",
        "",
        "> Generated from source code. Do not edit this file directly.",
        "",
        f"- Catalog version: `{catalog.catalog_version}`",
        f"- Source fingerprint: `{catalog.source_fingerprint[:16]}…`",
        f"- Scan root: `{catalog.scan_root}`",
        f"- Public callable symbols: **{len(public)}**",
        f"- API routes: **{len(catalog.routes)}**",
        "",
        "## Inventory Summary",
        "",
        "### By architectural layer",
        "",
        "| Layer | Public callables |",
        "|---|---:|",
    ]
    for name, count in sorted(by_layer.items()):
        out.append(f"| {name} | {count} |")

    out += ["", "### By role", "", "| Role | Public callables |", "|---|---:|"]
    for name, count in sorted(by_role.items()):
        out.append(f"| {name} | {count} |")

    out += ["", "## API Routes", "", "| Method | Path | Handler | Response model |", "|---|---|---|---|"]
    for route in catalog.routes:
        paths = "<br>".join(f"`{p}`" for p in route.full_paths) or f"`{route.local_path}`"
        response = f"`{route.response_model}`" if route.response_model else "—"
        out.append(f"| {route.method} | {paths} | `{route.handler_symbol}` | {response} |")

    grouped: dict[tuple[str, str], list[SymbolRecord]] = defaultdict(list)
    for symbol in public:
        grouped[(symbol.layer or "other", symbol.role or "other")].append(symbol)

    out += ["", "## Public Backend Symbols", ""]
    for (layer, role), symbols in sorted(grouped.items()):
        out.append(f"### {layer.title()} · {role.replace('_', ' ').title()}")
        out.append("")
        out.append("| Symbol | Signature | Purpose | Source |")
        out.append("|---|---|---|---|")
        for symbol in sorted(symbols, key=lambda s: s.symbol_id):
            purpose = _one_line_doc(symbol.docstring)
            source = f"`{symbol.source_file}:{symbol.source_line}`"
            out.append(f"| `{symbol.symbol_id}` | `{_sig(symbol)}` | {purpose or '—'} | {source} |")
        out.append("")

    out += ["## Dependency Detail", ""]
    for symbol in public:
        meaningful_calls = [c for c in symbol.calls if c.resolved and ("app." in c.resolved or c.resolved.startswith("app."))]
        if not meaningful_calls and not symbol.sql_files and not symbol.tables:
            continue
        out.append(f"### `{symbol.symbol_id}`")
        out.append("")
        if meaningful_calls:
            out.append("**Calls**")
            out.append("")
            for call in meaningful_calls:
                out.append(f"- `{call.resolved}`")
            out.append("")
        if symbol.called_by:
            out.append("**Called by**")
            out.append("")
            for caller in symbol.called_by:
                out.append(f"- `{caller}`")
            out.append("")
        if symbol.sql_files:
            out.append("**SQL templates**")
            out.append("")
            for name in symbol.sql_files:
                candidates = symbol.sql_file_candidates.get(name, [])
                suffix = ", ".join(f"`{p}`" for p in candidates) if candidates else "unresolved"
                out.append(f"- `{name}` → {suffix}")
            out.append("")
        if symbol.tables:
            out.append("**Tables detected**")
            out.append("")
            for table in symbol.tables:
                out.append(f"- `{table}`")
            out.append("")

    if catalog.warnings:
        out += ["## Scanner Warnings", ""]
        out.extend(f"- {warning}" for warning in catalog.warnings)
        out.append("")

    return "\n".join(out).rstrip() + "\n"


def write_outputs(catalog: CatalogRecord, output_dir: Path) -> tuple[Path, Path]:
    output_dir.mkdir(parents=True, exist_ok=True)
    json_path = output_dir / "backend_catalog.json"
    md_path = output_dir / "backend_catalog.md"
    json_path.write_text(render_json(catalog), encoding="utf-8")
    md_path.write_text(render_markdown(catalog), encoding="utf-8")
    return json_path, md_path
